; 卡车
{"sdkfz-305-1"
  {vehicle_view "car"}
}
{"sdkfz-305-2"
  {vehicle_view "opel_flak30"}
}
{"sdkfz-305-3"
  {vehicle_view "car"}
}
{"sdkfz-305-4"
  {vehicle_view "car"}
}
{"sdkfz-305-5"
  {vehicle_view "car"}
}

; 轮式装甲车
{"sdkfz-234-1"
  {vehicle_view "sdkfz234_1"}
}
{"sdkfz-234-2"
  {vehicle_view "puma"}
}
{"sdkfz-234-3"
  {vehicle_view "sdkfz234_3"}
}
{"sdkfz-234-4"
  {vehicle_view "sdkfz234_4"}
}

; 履带式装甲车
{"sdkfz-251-1"
  {vehicle_view "sdkfz251d_1"}
}
{"sdkfz-251-16"
  {vehicle_view "sdkfz251d_16"}
}
{"sdkfz-251-17"
  {vehicle_view "sdkfz251d_17"}
}
{"sdkfz-251-21"
  {vehicle_view "sdkfz251d_21"}
}
{"sdkfz-251-22"
  {vehicle_view "sdkfz251d_22"}
}

; 坦克
{"panzer-4-h"
  {vehicle_view "panzer4j"}
}
{"panzer-4-j"
  {vehicle_view "panzer4j"}
}

{"panzer-5-a"
  {vehicle_view "panzer5"}
}
{"panzer-5-d"
  {vehicle_view "panzer5"}
}
{"panzer-5-g"
  {vehicle_view "panzer5"}
}

{"panzer-6-e"
  {vehicle_view "tiger_1h"}
}
{"panzer-6-h"
  {vehicle_view "tiger_1h"}
}
