; standard third person control vision for INF

; 卡车
{"sdkfz-305-1" inherit "vehicle custom.truck"}
{"sdkfz-305-2" inherit "vehicle custom.truck.flak30"}
{"sdkfz-305-3" inherit "vehicle custom.truck"}
{"sdkfz-305-4" inherit "vehicle custom.truck"}
{"sdkfz-305-5" inherit "vehicle custom.truck"}

; 轮式装甲车
{"sdkfz-234-1" inherit "vehicle custom.armored-car.sdkfz234-1"}
{"sdkfz-234-2" inherit "vehicle custom.armored-car.sdkfz234-2"}
{"sdkfz-234-3" inherit "vehicle custom.armored-car.sdkfz234-3"}
{"sdkfz-234-4" inherit "vehicle custom.armored-car.sdkfz234-4"}

; 履带式装甲车
{"sdkfz-251-1"       inherit "vehicle custom.armored-car.sdkfz251"}
{"sdkfz-251-16"      inherit "vehicle custom.armored-car.sdkfz251"}
{"sdkfz-251-17"      inherit "vehicle custom.armored-car.sdkfz251.17"}
{"sdkfz-251-21"      inherit "vehicle custom.armored-car.sdkfz251.21"}
{"sdkfz-251-22"      inherit "vehicle custom.armored-car.sdkfz251.22"}

; 自行火炮 / 自行榴弹炮
{"sdkfz-124" inherit "vehicle custom.spg"}

; 坦克
{"panzer-4-h" inherit "vehicle custom.tank.panzer4-h"}
{"panzer-4-j" inherit "vehicle custom.tank.panzer4-h"}

{"panzer-5-a" inherit "vehicle custom.tank"}
{"panzer-5-d" inherit "vehicle custom.tank"}
{"panzer-5-d-ace" inherit "vehicle custom.tank"}
{"panzer-5-g" inherit "vehicle custom.tank"}

{"panzer-6-e"     inherit "vehicle custom.tank.tiger-e"}
{"panzer-6-e-ace" inherit "vehicle custom.tank.tiger-e"}
{"panzer-6-h"     inherit "vehicle custom.tank.tiger-h"}

{"panzer-6-b-h"     inherit "vehicle custom.tank.tiger2-h"}
{"panzer-6-b-h-ace" inherit "vehicle custom.tank.tiger2-h"}
{"panzer-6-b-p"     inherit "vehicle custom.tank.tiger2-p"}

; 自行榴弹炮
{"pzh2000" inherit "vehicle custom.tank.e-100"}
