; Vision abilities for use with sniper rifles and binoculars

(define "standard_vision"
  {Vision standard-human-vision}
)

(define "elite_vision"
  {Vision standard-human-vision-elite}
)

(define "recon_vision"
  {Vision standard-human-vision-recon}
)

(define "sniper_vision"
  {"telescope"}
  {"aimedshot"}
  {Vision standard-human-vision-sniper}
)

(define "binocular_vision"
  {"field_glass"}
  {Vision standard-human-vision-elite}
)
