import { i0lines } from '../../../utils/formatter.mjs';

export type SetTankDurabilityOptions = {
  body: number;
  engine: number;
  turret: number;
  mantlet: number;
  gun: number;
  track: number;
  armor: number;
};

/** 设置坦克耐久 */
export const setTankDurability = (options: SetTankDurabilityOptions) => {

  const { body, engine, mantlet, turret, gun, track, armor } = options;

  return i0lines(
    '{perks',
    '  {component "body"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 10}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "bodyback"',
    '    {health',
    `      {hp ${body}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "cabin"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 0.8}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "engine"',
    '    {health',
    `      {hp ${engine}}`,
    `      {hp_broken ${engine}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "mantlet"',
    '    {health',
    `      {hp ${mantlet}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "turret"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "aux_turret1"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "aux_turret2"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "gun"',
    '    {health',
    `      {hp ${gun}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "trackleft"',
    '    {health',
    `      {hp ${track}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "trackright"',
    '    {health',
    `      {hp ${track}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "shield_cover"',
    '    {health',
    `      {hp ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "wheel"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    '    }',
    '    {armor_damage_modifier 5}',
    '  }',
    '  {component tag "glass"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    `      {hp_broken ${armor * 0.5}}`,
    '    }',
    '  }',
    '  {component tag "lamp"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    `      {hp_broken ${armor * 0.5}}`,
    '    }',
    '  }',
    '  {component tag "shield"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "cut_part"',
    '    {health',
    `      {hp ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "fuel"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "ammo"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "rocket"',
    '    {health',
    '      {hp 100}',
    '      {hp_broken 100}',
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "transmission"',
    '    {health',
    `      {hp ${engine}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '}',
  );

};

export type SetCarDurabilityOptions = {
  body: number;
  engine: number;
};

/** 设置汽车耐久 */
export const setCarDurability = (options: SetCarDurabilityOptions) => {

  const { body, engine } = options;

  return i0lines(
    setTankDurability({ body, engine, turret: 100, mantlet: 100, gun: 150, track: 100, armor: 50 }),
    '{volume "body"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body1"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body2"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body3"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body4"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body5"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body6"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body7"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body8"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body9"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback1"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback2"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback3"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback4"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback5"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback6"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback7"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback8"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback9"  ',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback10"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback11"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback12"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback13"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback14"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback15"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback16"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback17"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback18"',
    `  {thickness ${body}}`,
    '}',
    '{volume "bodyback19"',
    `  {thickness ${body}}`,
    '}',
    '{volume "engine"',
    `  {thickness ${engine}}`,
    '}',
    '{volume "engine1"',
    `  {thickness ${engine}}`,
    '}',
    '{volume "engine2"',
    `  {thickness ${engine}}`,
    '}',
  );

};

export type SetMotoDurabilityOptions = {
  body: number;
  engine: number;
};

/** 设置摩托耐久 */
export const setMotoDurability = (options: SetMotoDurabilityOptions) => {

  const { body, engine } = options;

  return i0lines(
    '{perks',
    '  {component "body"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 10}}`,
    '    }',
    '    {armor_damage_modifier 2}',
    '  }',
    '  {component "engine"',
    '    {health',
    `      {hp ${engine}}`,
    `      {hp_broken ${engine}}`,
    '    }',
    '    {armor_damage_modifier 3}',
    '  }',
    '  {component tag "wheel"',
    '    {health',
    '      {hp 125}',
    '    }',
    '    {armor_damage_modifier 5}',
    '  }',
    '  {component tag "glass"',
    '    {health',
    '      {hp 60}',
    '      {hp_broken 60}',
    '    }',
    '  }',
    '  {component tag "shield"',
    '    {health',
    '      {hp 100}',
    '      {hp_broken 100}',
    '    }',
    '  }',
    '  {component tag "cut_part"',
    '    {health',
    '      {hp 100}',
    '    }',
    '  }',
    '  {component tag "fuel"',
    '    {health',
    '      {hp 100}',
    '      {hp_broken 100}',
    '    }',
    '    {armor_damage_modifier 3}',
    '  }',
    '  {component tag "ammo"',
    '    {health',
    '      {hp 100}',
    '      {hp_broken 100}',
    '    }',
    '    {armor_damage_modifier 3}',
    '  }',
    '}',
    '{volume "body"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body1"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body2"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body3"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body4"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body5"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body6"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body7"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body8"',
    `  {thickness ${body}}`,
    '}',
    '{volume "body9"',
    `  {thickness ${body}}`,
    '}',
    '{volume "engine"',
    `  {thickness ${engine}}`,
    '}',
    '{volume "engine1"',
    `  {thickness ${engine}}`,
    '}',
    '{volume "engine2"',
    `  {thickness ${engine}}`,
    '}',
    '{volume "fuel"',
    '  {tags "explosive"}',
    '  {thickness 1}',
    '}',
  );
};

export type SetCannonDurabilityOptions = {
  body: number;
  gun: number;
  wheel: number;
  shield: number;
  thickness: number;
};

/** 设置牵引式火炮耐久 */
export const setCannonDurability = (options: SetCannonDurabilityOptions) => {

  const { body, gun, wheel, shield, thickness } = options;

  return i0lines(
    '{perks',
    '  {component "body"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 10}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "gun"',
    '    {health',
    `      {hp ${gun}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "wheel"',
    '    {health',
    `      {hp ${wheel}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "shield"',
    '    {health',
    `      {hp ${shield}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '}',
    '{volume "body"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body1"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body2"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body3"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body4"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body5"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body6"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body7"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body8"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body9"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body10"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body11"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body12"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body13"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body14"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body15"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body16"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body17"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body18"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body19"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "body20"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standc"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standr"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standl"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standr1"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standr2"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standl1"',
    `  {thickness ${thickness}}`,
    '}',
    '{volume "standl2"',
    `  {thickness ${thickness}}`,
    '}',
  );

};
