; car
{"blitz3_6" inherit "vehicle custom.truck"}
{"blitz3_6_art_ammo" inherit "vehicle custom.truck"}
{"blitz3_6_engineering" inherit "vehicle custom.truck"}
{"blitz3_6_fuel" inherit "vehicle custom.truck"}
{"blitz3_6_radio" inherit "vehicle custom.truck"}
{"blitz3_6_flak30" inherit "vehicle custom.truck.flak30"}

; armored car
{"sdkfz251d_1"       inherit "vehicle custom.armored-car.sdkfz251"}
{"sdkfz251d_1_stuka" inherit "vehicle custom.armored-car.sdkfz251"}
{"sdkfz251d_16"      inherit "vehicle custom.armored-car.sdkfz251"}
{"sdkfz251d_17"      inherit "vehicle custom.armored-car.sdkfz251.17"}
{"sdkfz251d_21"      inherit "vehicle custom.armored-car.sdkfz251.21"}
{"sdkfz251d_22"      inherit "vehicle custom.armored-car.sdkfz251.22"}
{"sdkfz231" inherit "vehicle custom.armored-car.sdkfz231"}
{"sdkfz234_1" inherit "vehicle custom.armored-car.sdkfz234-1"}
{"sdkfz234_2" inherit "vehicle custom.armored-car.sdkfz234-2"}
{"sdkfz234_3" inherit "vehicle custom.armored-car.sdkfz234-3"}
{"sdkfz234_4" inherit "vehicle custom.armored-car.sdkfz234-4"}
{"panzerwerfer42" inherit "vehicle custom.spg"}

; tank
{"panzer2l" inherit "vehicle custom.tank.panzer2l"}
{"hetzer" inherit "vehicle custom.tank.hetzer"}
{"marder3m" inherit "vehicle custom.tank.marder3-m"}
{"grille_m" inherit "vehicle custom.tank.grille-m"}
{"grille_k" inherit "vehicle custom.spg.grille-k"}
{"stug3f" inherit "vehicle custom.tank.stug3"}
{"stug3g" inherit "vehicle custom.tank.stug3"}
{"stug3g_late" inherit "vehicle custom.tank.stug3"}
{"stuh42" inherit "vehicle custom.tank.stuh42"}
{"panzer3m" inherit "vehicle custom.tank.panzer3-m"}
{"panzer3n" inherit "vehicle custom.tank.panzer3-n"}
{"panzer4g" inherit "vehicle custom.tank.panzer4-g"}
{"panzer4h" inherit "vehicle custom.tank.panzer4-h"}
{"wirbelwind" inherit "vehicle custom.tank.wirbelwind"}
{"ostwind" inherit "vehicle custom.tank.ostwind"}
{"wespe" inherit "vehicle custom.spg"}
{"hummel" inherit "vehicle custom.spg"}
{"panzer5a" inherit "vehicle custom.tank"}
{"panzer5d" inherit "vehicle custom.tank"}
{"panzer5g" inherit "vehicle custom.tank"}
{"tiger1e" inherit "vehicle custom.tank.tiger-e"}
{"tiger1h" inherit "vehicle custom.tank.tiger-h"}
{"tiger1hunt" inherit "vehicle custom.tank.tiger-e"}
{"tiger2p" inherit "vehicle custom.tank.tiger2-p"}
{"tiger2h" inherit "vehicle custom.tank.tiger2-h"}
{"jagdpanther" inherit "vehicle custom.tank.jagdpanther"}
{"ferdinand" inherit "vehicle custom.tank.e-100"}
{"sturmtiger" inherit "vehicle custom.tank.sturmtiger"}
{"jagdtiger" inherit "vehicle custom.tank.jagdtiger"}

; IInfinity Series
{"tank-ai-bomb" inherit "vehicle custom.tank.ai-bomb"}
{"tank-e-25"  inherit "vehicle custom.tank.e-25"}
{"tank-e-50"  inherit "vehicle custom.tank.e-50"}
{"tank-e-75"  inherit "vehicle custom.tank.e-75"}
{"tank-e-100" inherit "vehicle custom.tank.e-100"}
