import { i0lines } from '../../../../utils/formatter.mjs';
import { type PresetLevel } from '../shared.mjs';

export const TankDurabilityPresets: Record<PresetLevel, SetTankDurabilityOptions> = {
  Level01: {
    $options: 'tank',
    body: 200,
    engine: 100,
    turret: 200,
    mantlet: 100,
    gun: 150,
    track: 150,
    armor: 50,
  },
  Level02: {
    $options: 'tank',
    body: 300,
    engine: 125,
    turret: 250,
    mantlet: 125,
    gun: 150,
    track: 150,
    armor: 50,
  },
  Level03: {
    $options: 'tank',
    body: 350,
    engine: 150,
    turret: 300,
    mantlet: 150,
    gun: 200,
    track: 200,
    armor: 100,
  },
  Level04: {
    $options: 'tank',
    body: 400,
    engine: 150,
    turret: 350,
    mantlet: 175,
    gun: 200,
    track: 200,
    armor: 100,
  },
  Level05: {
    $options: 'tank',
    body: 500,
    engine: 175,
    turret: 400,
    mantlet: 200,
    gun: 250,
    track: 250,
    armor: 100,
  },
  Level06: {
    $options: 'tank',
    body: 600,
    engine: 200,
    turret: 400,
    mantlet: 200,
    gun: 250,
    track: 250,
    armor: 150,
  },
  Level07: {
    $options: 'tank',
    body: 700,
    engine: 225,
    turret: 450,
    mantlet: 225,
    gun: 300,
    track: 300,
    armor: 150,
  },
  Level08: {
    $options: 'tank',
    body: 800,
    engine: 250,
    turret: 500,
    mantlet: 250,
    gun: 300,
    track: 300,
    armor: 150,
  },
  Level09: {
    $options: 'tank',
    body: 900,
    engine: 300,
    turret: 600,
    mantlet: 300,
    gun: 350,
    track: 350,
    armor: 200,
  },
  Level10: {
    $options: 'tank',
    body: 1000,
    engine: 350,
    turret: 650,
    mantlet: 325,
    gun: 350,
    track: 350,
    armor: 200,
  },
} as const;

export type SetTankDurabilityOptions = {
  /** 载具类型 */
  $options: 'tank';
  /** 车体耐久 */
  body: number;
  /** 引擎耐久 */
  engine: number;
  /** 炮塔耐久 */
  turret: number;
  /** 炮塔耐久 */
  mantlet: number;
  /** 炮管耐久 */
  gun: number;
  /** 履带耐久 */
  track: number;
  /** 装甲耐久 */
  armor: number;
};

/** 设置坦克耐久 */
export const setTankDurability = (options: SetTankDurabilityOptions) => {

  const { body, engine, mantlet, turret, gun, track, armor } = options;

  return i0lines(
    '{perks',
    '  {component "body"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 10}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "bodyback"',
    '    {health',
    `      {hp ${body}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "cabin"',
    '    {health',
    `      {hp ${body}}`,
    `      {hp_broken ${body * 0.8}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "engine"',
    '    {health',
    `      {hp ${engine}}`,
    `      {hp_broken ${engine}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "mantlet"',
    '    {health',
    `      {hp ${mantlet}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "turret"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "aux_turret1"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "aux_turret2"',
    '    {health',
    `      {hp ${turret}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "gun"',
    '    {health',
    `      {hp ${gun}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "trackleft"',
    '    {health',
    `      {hp ${track}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "trackright"',
    '    {health',
    `      {hp ${track}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component "shield_cover"',
    '    {health',
    `      {hp ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "wheel"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    '    }',
    '    {armor_damage_modifier 5}',
    '  }',
    '  {component tag "glass"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    `      {hp_broken ${armor * 0.5}}`,
    '    }',
    '  }',
    '  {component tag "lamp"',
    '    {health',
    `      {hp ${armor * 0.5}}`,
    `      {hp_broken ${armor * 0.5}}`,
    '    }',
    '  }',
    '  {component tag "shield"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "cut_part"',
    '    {health',
    `      {hp ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "fuel"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "ammo"',
    '    {health',
    `      {hp ${armor}}`,
    `      {hp_broken ${armor}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "rocket"',
    '    {health',
    '      {hp 100}',
    '      {hp_broken 100}',
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '  {component tag "transmission"',
    '    {health',
    `      {hp ${engine}}`,
    '    }',
    '    {armor_damage_modifier 0.1}',
    '  }',
    '}',
  );

};
