import { i0lines, i2lines } from '../../../utils/formatter.mjs';

export const ArmorPresets = {
  cannon: 10,
  moto: 5,
  car: 10,
  lightTank: 20,
  mediumTank: 30,
  heavyTank: 40,
} as const;

const setArmor = (name: string) => (
  i2lines(
    `{setting "${name}"`,
    '  {threshold',
    '    {blast {koef 0.5}}',
    '    {pierce {koef 0.8}}',
    '  }',
    `  {volumes "${name}*"}`,
    '}',
  )
);

/** 设置基础装甲 */
export const setBasicArmor = (armor: number) => (
  i0lines(
    '{armor',
    '  ; Common',
    `  ${setArmor('body')}`,
    `  ${setArmor('turret')}`,
    `  ${setArmor('aux_turret1')}`,
    `  ${setArmor('aux_turret2')}`,
    `  ${setArmor('aux_turret3')}`,
    `  ${setArmor('aux_turret4')}`,
    `  ${setArmor('gun')}`,
    `  ${setArmor('barrel')}`,
    `  ${setArmor('mantlet')}`,
    `  ${setArmor('cupola')}`,
    `  ${setArmor('hatch')}`,
    `  ${setArmor('engine')}`,
    `  ${setArmor('track')}`,
    `  ${setArmor('wheel')}`,
    `  ${setArmor('transmission')}`,
    `  ${setArmor('fuel')}`,
    `  ${setArmor('breach')}`,
    `  ${setArmor('breech')}`,
    `  ${setArmor('shield')}`,
    `  ${setArmor('tshield')}`,
    `  ${setArmor('armor')}`,
    `  ${setArmor('glass')}`,
    `  ${setArmor('window')}`,
    `  ${setArmor('lamp')}`,
    `  ${setArmor('sandbag')}`,
    `  ${setArmor('detail')}`,
    `  ${setArmor('grill')}`,
    `  ${setArmor('roller')}`,
    `  ${setArmor('swingarm')}`,
    '  ; Car',
    `  ${setArmor('cabin')}`,
    `  ${setArmor('bodyback')}`,
    `  ${setArmor('door')}`,
    '  ; Cannon',
    `  ${setArmor('stand')}`,
    `  ${setArmor('box')}`,
    `  ${setArmor('magazine')}`,
    '  ; Airborne',
    `  ${setArmor('stabilizer')}`,
    `  ${setArmor('wingl')}`,
    `  ${setArmor('wingr')}`,
    `  ${setArmor('blade')}`,
    `  ${setArmor('spin')}`,
    `  ${setArmor('canopy')}`,
    `  ${setArmor('elevator')}`,
    `  ${setArmor('rudder')}`,
    `  ${setArmor('aileron')}`,
    `  ${setArmor('gear_')}`,
    '  ; Ammo',
    '  {setting "ammo"',
    '    {threshold',
    `      {blast  {koef (* ${armor} 1.00)}}          ; koef = coefficient. Threshold = koef value x volume effective thickness`,
    '      {pierce {koef 1}}',
    '    }',
    '    {volumes "ammo*"}',
    '  }',
    '  {setting "rocket"',
    '    {threshold',
    `      {blast  {koef (* ${armor} 0.25)}} ; koef = coefficient. Threshold = koef value x volume effective thickness`,
    '      {pierce {koef 1}}',
    '    }',
    '    {volumes "rocket*"}',
    '  }',
    '}',
  )
);
